#nginx-data container
MAINTAINER Vincent Flesouras
LABEL description="This is a container I use to house \
data from several different apps. It is generic and very  \
small in size. " \
FROM alpine:latest
VOLUME /app
CMD["true"]